language: ruby
rvm:
  - 2.1.2
gemfile:
  - gemfiles/rails_4.0_mysql2_driver.gemfile
  - gemfiles/rails_4.0_pg_driver.gemfile
  - gemfiles/rails_4.0_sqlite3_driver.gemfile
  - gemfiles/rails_4.1_mysql2_driver.gemfile
  - gemfiles/rails_4.1_pg_driver.gemfile
  - gemfiles/rails_4.1_sqlite3_driver.gemfile
before_script:
  - "cd spec/dummy && RAILS_ENV=test bundle exec rake db:create db:migrate && cd -"
